version: '3'
services:
  proxy:
    image: 'jwilder/nginx-proxy:latest'
    ports:
      - '80:80'
    volumes:
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
  db:
    image: 'mysql:5.7'
    ports:
      - '3306'
    volumes:
      - './config/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './mysql:/var/lib/mysql'
      - './data:/usr/local/share/data'
    environment:
      - 'MYSQL_ROOT_PASSWORD'
      - 'MYSQL_USER'
      - 'MYSQL_PASSWORD'
      - 'MYSQL_DATABASE'
  memcached:
    image: 'memcached:1.5'
  redis:
    image: 'redis:4.0.11'
    volumes:
      - './config/redis.conf:/usr/local/etc/redis/redis.conf'
  app:
    build:
      context: .
      args:
        BUILD_ENV: $BUILD_ENV
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - './project:/usr/src/app/myproject'
      - './media:/usr/src/app/media'
      - './static:/usr/src/app/static'
      - './site_static:/usr/src/app/site_static'
      - './templates:/usr/src/app/templates'
      - './apps/artists:/usr/src/app/artists'
      - './apps/auth_extra:/usr/src/app/auth_extra'
      - './apps/bulletin_board:/usr/src/app/bulletin_board'
      - './apps/cms_extensions:/usr/src/app/cms_extensions'
      - './apps/custom_admin:/usr/src/app/custom_admin'
      - './apps/cv:/usr/src/app/cv'
      - './apps/demo_app:/usr/src/app/demo_app'
      - './apps/editorial:/usr/src/app/editorial'
      - './apps/email_messages:/usr/src/app/email_messages'
      - './apps/external:/usr/src/app/external'
      - './apps/external_auth:/usr/src/app/external_auth'
      - './apps/ideas:/usr/src/app/ideas'
      - './apps/likes:/usr/src/app/likes'
      - './apps/locations:/usr/src/app/locations'
      - './apps/magazine:/usr/src/app/magazine'
      - './apps/movies:/usr/src/app/movies'
      - './apps/myapp1:/usr/src/app/myapp1'
      - './apps/myapp2:/usr/src/app/myapp2'
      - './apps/products:/usr/src/app/products'
      - './apps/quotes:/usr/src/app/quotes'
      - './apps/search:/usr/src/app/search'
      - './apps/utils:/usr/src/app/utils'
    ports:
      - '8000:8000'
    environment:
      - 'AUTH0_DOMAIN'
      - 'AUTH0_KEY'
      - 'AUTH0_SECRET'
      - 'DJANGO_USE_DEBUG'
      - 'DJANGO_USE_DEBUG_TOOLBAR'
      - 'SITE_HOST'
      - 'MEDIA_HOST'
      - 'STATIC_HOST'
      - 'VIRTUAL_HOST=${SITE_HOST}'
      - 'VIRTUAL_PORT=8000'
      - 'MYSQL_HOST=db'
      - 'MYSQL_USER'
      - 'MYSQL_PASSWORD'
      - 'MYSQL_DATABASE'
      - 'MAPS_API_KEY'
      - 'CACHE_LOCATION=memcached:11211'
      #- 'CACHE_LOCATION=redis://redis:6379'
  media:
    image: 'httpd:latest'
    volumes:
      - './media:/usr/local/apache2/htdocs'
    ports:
      - '80'
    environment:
      - 'VIRTUAL_HOST=${MEDIA_HOST}'
  static:
    image: 'httpd:latest'
    volumes:
      - './static:/usr/local/apache2/htdocs'
      - './config/httpd.conf:/usr/local/apache2/conf/httpd.conf'
    ports:
      - '80'
    environment:
      - 'VIRTUAL_HOST=${STATIC_HOST}'
